# Generated by Django 4.1.5 on 2023-01-15 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_products_product_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
