# Generated by Django 4.1.5 on 2023-01-30 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='merchant_id',
            new_name='payment_intent',
        ),
    ]
